workflows:
  ios-workflow:
    name: iOS Build and Publish
    max_build_duration: 120
    instance_type: mac_mini_m2
    
    environment:
      vars:
        XCODE_WORKSPACE: AIChatApp.xcworkspace
        XCODE_SCHEME: AIChatApp
        APP_STORE_CONNECT_API_KEY_ID: $APP_STORE_CONNECT_API_KEY_ID
        APP_STORE_CONNECT_API_ISSUER_ID: $APP_STORE_CONNECT_API_ISSUER_ID
        APP_STORE_CONNECT_API_KEY_CONTENT: $APP_STORE_CONNECT_API_KEY_CONTENT
        CF_BUNDLE_VERSION: $BUILD_NUMBER
        CF_BUNDLE_SHORT_VERSION_STRING: $APP_STORE_CONNECT_APP_VERSION
    
    scripts:
      - name: Install dependencies
        script: |
          # Install CocoaPods if needed
          which pod || gem install cocoapods
          pod install --repo-update
    
      - name: Set up code signing
        script: |
          # Import certificates and profiles
          security create-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
          
          # Import certificates
          echo "$CERTIFICATES_P12" | base64 --decode -o certificates.p12
          security import certificates.p12 -k build.keychain -P "$CERTIFICATES_PASSWORD" -T /usr/bin/codesign
          
          # Import provisioning profiles
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          echo "$PROVISIONING_PROFILE" | base64 --decode -o ~/Library/MobileDevice/Provisioning\ Profiles/profile.mobileprovision
    
      - name: Build iOS app
        script: |
          # Set build number
          xcodebuild -version
          xcodebuild -workspace "$XCODE_WORKSPACE" -scheme "$XCODE_SCHEME" -configuration Release -destination generic/platform=iOS \
            -allowProvisioningUpdates \
            -setVersionNumber "$CF_BUNDLE_VERSION" \
            -setVersionString "$CF_BUNDLE_SHORT_VERSION_STRING" \
            clean build
    
    artifacts:
      - AIChatApp/**/*.app
      - AIChatApp/**/*.app.dSYM.zip
    
    publishing:
      app_store_connect:
        api_key: 
          id: $APP_STORE_CONNECT_API_KEY_ID
          issuer_id: $APP_STORE_CONNECT_API_ISSUER_ID
          key_content: $APP_STORE_CONNECT_API_KEY_CONTENT
        submit_to_testflight: true
        submit_to_app_store: false
        wait_for_processing: false
        release_status: "BETA"
        release_notes: |
          iOS 15.8.4 uyumlu AI Agent uygulaması.
          - Yeni özellikler ve hata düzeltmeleri.
          - OpenAI ve OpenRouter servis desteği.
          - Agent profilleri ve hafıza sistemi.
          - Web arama entegrasyonu.
content>
</write_to_file>
